-- ~/.config/nvim/init.lua
--
-- phiOS — minimal Neovim configuration.
--
-- Deliberately plugin-free: only built-in features are used, so nothing
-- depends on a plugin manager or external packages. Modules live in lua/
-- and are loaded through the standard runtimepath lookup (require("x")
-- resolves to lua/x.lua).

-- Core editor behaviour
require("options")
require("keymaps")

-- File explorer (built-in netrw)
require("netrw")

-- Chroma keyboard integration (phiOS). Never edit this file.
require("phi_chroma")

-- UI components, loaded before the theme so the theme can restyle them
require("statusline")

-- Theme: generated by phiOS scripts from design/ tokens; it exists at
-- runtime but is not tracked here. Loaded last, as the single source of
-- every colour, font and size in the editor.
require("theme")