-- ~/.config/nvim/init.lua
--
-- phiOS — minimal Neovim configuration: the editor behind $EDITOR, $VISUAL,
-- sudoedit and git commit, and the only one on `mini`.
--
-- Deliberately plugin-free: only built-in features are used, so nothing
-- depends on a plugin manager or external packages. The options, keymaps,
-- statusline, theme and Chroma integration shared with nvim-code and
-- nvim-notes live in ~/.config/nvim-common, prepended to the runtimepath so
-- require() finds them there.

local common = vim.fs.joinpath(vim.env.XDG_CONFIG_HOME or vim.fs.normalize("~/.config"), "nvim-common")
vim.opt.runtimepath:prepend(common)

-- Core editor behaviour
require("phi.options")
require("phi.keymaps")
require("keymaps")

-- File explorer (built-in netrw)
require("netrw")

-- Chroma keyboard integration (phiOS). Never edit this file.
require("phi_chroma")

-- UI components, loaded before the theme so the theme can restyle them
require("phi.statusline")

-- Theme: generated by phiOS scripts from design/ tokens; it exists at
-- runtime but is not tracked here. Loaded last, as the single source of
-- every colour, font and size in the editor.
require("theme")
